version: 2.1

jobs:
  automated-api-tests:
    macos:
      xcode: 13.4.1
    steps:
      - checkout
      - run:
          name: Install Node.js and Newman
          command: |
            brew install node
            npm install -g newman
      - run:
          name: Login using your API key
          command: postman login --with-api-key $POSTMAN_API_KEY
      - run:
          name: Run Postman Collection with Newman
          command: |
            newman run "Postman Collections/Click up.json" --reporters cli,html --reporter-html-export results/report.html

workflows:
  version: 2
  automated-api-tests:
    jobs:
      - automated-api-tests
