version: 2.1

jobs:
  automated-api-tests:
    macos:
      xcode: 13.4.1
    steps:
      - checkout
      - run:
          name: Install Postman CLI
          command: |
            curl -o- "https://dl-cli.pstmn.io/install/osx_64.sh" | sh
      - run:
          name: Login using your API key
          command: postman login --with-api-key $POSTMAN_API_KEY
      - run: |
            postman collection run "Postman Collections/ClickUp_Api_tests.json" --integration-id "166385-${CIRCLE_WORKFLOW_JOB_ID}"

workflows:
  version: 2
  automated-api-tests:
    jobs:
      - automated-api-tests
