version: 2.1

jobs:
  automated-api-tests:
    macos:
      xcode: 13.4.1
    steps:
      - checkout
      - run:
          name: Install Rosetta 2
          command: |
            /usr/sbin/softwareupdate --install-rosetta --agree-to-license
      - run:
           name: Install Node.js and Newman
           command: |
             brew install node
             npm install -g newman
             npm install -g newman-reporter-html
      - run:
          name: Verify Node.js and Newman installation
          command: |
            echo "Verifying Node.js and npm installation..."
            node -v
            npm -v
            echo "Verifying Newman installation..."
            newman -v
      - run:
          name: Verify Postman installation
          command: |
            postman --version
      - run:
          name: Run Postman collection
          command: |
            COLLECTION_PATH="Postman Collections/Click up.json"
            if [ ! -f "$COLLECTION_PATH" ]; then
              echo "Collection file $COLLECTION_PATH does not exist"
              exit 1
            fi
            postman collection run "$COLLECTION_PATH"

workflows:
  version: 2
  automated-api-tests:
    jobs:
      - automated-api-tests
